// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXeTptmDR_oRIGfnVcVmWwQz8O_hwd7XA',
    appId: '1:207555399227:web:84f0970ba4444a534d561e',
    messagingSenderId: '207555399227',
    projectId: 'project-e5599',
    authDomain: 'project-e5599.firebaseapp.com',
    storageBucket: 'project-e5599.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtVrajirf93EuEyruckDx7t0bTkWpJQ7Y',
    appId: '1:207555399227:android:283294dc219c23304d561e',
    messagingSenderId: '207555399227',
    projectId: 'project-e5599',
    storageBucket: 'project-e5599.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY9SAY7YIc3ovisGeyc-N3NPqNPkfDeh0',
    appId: '1:207555399227:ios:7aefc5d0d6df4ba14d561e',
    messagingSenderId: '207555399227',
    projectId: 'project-e5599',
    storageBucket: 'project-e5599.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY9SAY7YIc3ovisGeyc-N3NPqNPkfDeh0',
    appId: '1:207555399227:ios:7aefc5d0d6df4ba14d561e',
    messagingSenderId: '207555399227',
    projectId: 'project-e5599',
    storageBucket: 'project-e5599.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXeTptmDR_oRIGfnVcVmWwQz8O_hwd7XA',
    appId: '1:207555399227:web:005bee893c6cd4b04d561e',
    messagingSenderId: '207555399227',
    projectId: 'project-e5599',
    authDomain: 'project-e5599.firebaseapp.com',
    storageBucket: 'project-e5599.firebasestorage.app',
  );

}